services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    networks:
      - pg-network

  db:
    image: postgres:16
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    networks:
      - pg-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  db-test:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: carRentalTest
      POSTGRES_USER: test
    networks:
      - pg-network
    volumes:
      - ./backend/src/main/resources/db/migration/V1__schema.sql:/docker-entrypoint-initdb.d/V1__schema.sql

networks:
  pg-network:
volumes:
  postgres_data: